sonar.projectKey=feliperochadev_little-words
sonar.organization=feliperochadev
sonar.sources=app,src
sonar.tests=__tests__
sonar.exclusions=**/node_modules/**,**/android/**,**/ios/**,**/coverage/**
sonar.test.inclusions=__tests__/**/*.{ts,tsx,js,jsx}
